spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Student Service
spring.cloud.gateway.routes[0].id=student-service
spring.cloud.gateway.routes[0].uri=lb://student-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/students/**

# Attendance Service
spring.cloud.gateway.routes[1].id=attendance-service
spring.cloud.gateway.routes[1].uri=lb://attendance-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/attendance/**

# Auth Service
spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**

# Leave Service
spring.cloud.gateway.routes[3].id=leave-service
spring.cloud.gateway.routes[3].uri=lb://leave-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/leaves/**

# Room Service
spring.cloud.gateway.routes[4].id=room-service
spring.cloud.gateway.routes[4].uri=lb://room-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/rooms/**

# Fee Service
spring.cloud.gateway.routes[5].id=fee-service
spring.cloud.gateway.routes[5].uri=lb://fee-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/fees/**

# Complaint Service
spring.cloud.gateway.routes[6].id=complaint-service
spring.cloud.gateway.routes[6].uri=lb://complaint-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/complaints/**

# Mess Service
spring.cloud.gateway.routes[7].id=mess-service
spring.cloud.gateway.routes[7].uri=lb://mess-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/mess/**

# Notification Service
spring.cloud.gateway.routes[8].id=notification-service
spring.cloud.gateway.routes[8].uri=lb://notification-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/notifications/**
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration